### ISSUE TITLE
Discuss user scenarios

### ISSUE THREAD

**Issue by lakruzz** [Praqma/GSheets2TBoards#3]
Assess the current features, and how they map to @JasmineCrozier real needs

...let's write a few _user story poems_

**Comment by JasmineCrozier** [comment]
the Trello board that I want (except Speakers, and confirmed speakers)
https://trello.com/b/rIdY6vt6/code-oslo-3-05-17

the sheet:
https://docs.google.com/a/praqma.net/spreadsheets/d/1t_P9DlJuSSuApfTXFN5dwk0ApkX-q4n8hMIOYx_rZSw/edit?usp=sharing

**Comment by lakruzz** [comment]
I'm adding a template version of the sheet:

https://docs.google.com/spreadsheets/d/1HFU0lhE45XY7yQTgo35wRKJtNneKma87tES9M82LnGQ/

**Comment by timea** [comment]
The topics were discussed in the meeting. I am breaking this out into issues and closing this. If any new requests come to mind, please file new issues @lakruzz @JasmineCrozier.

**Comment by timea** [comment]
Hey there :) @JasmineCrozier 

I have listed out our use cases in issues as you can see just above.

Can you take a look if they are okay? Anything to add?

**Comment by JasmineCrozier** [comment]
Thank you @timea 
I do not know if it makes a difference but regarding #11 
"As a user, I want to be able to configure the members of my new Trello board in the Google Sheet, so the colleagues I need to work with on this board " have access to the new board 
( instead of "are notified of the creation of this board")

One more "user request" that I would like to add, if possible: 
As a user, I would like that the cards on my new Trello board appear in chronological order of the due date (closest due date at the top), so that I can quickly see what is the most urgent.

**Comment by timea** [comment]
Thanks @JasmineCrozier ! Made the modification to #11 and created #15. :)
